local_backend: true
media_folder: src/content/images
public_folder: src/content/images

backend:
  name: git-gateway
  repo: username/reponame
  branch: main

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    media_folder: ../images
    public_folder: ../images
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["blog"] }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    media_folder: ../images
    public_folder: ../images
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
