backend:
  name: git-gateway
  repo: username/reponame
  branch: main
local_backend: true
media_folder: src/content/img
public_folder: src/content/img

collections:
  - name: "post"
    label: "Post"
    folder: "src/content/post"
    create: true
    media_folder: ../img
    public_folder: ../img
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["blog"] }

  - name: "page"
    label: "Page"
    folder: "src/content/page"
    create: true
    media_folder: ../img
    public_folder: ../img
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
